AcademySoftwareFoundation/openfx

- scripts/genRelease
scripts/genRelease is the script that builds OFX releases, builds and
packages the headers and doc, and uploads to the OFX Association
website.  When doing test builds it's inconvenient to have to have a
clean git working dir because you have to commit everything each time.
I added a --dirty arg to allow doing test builds.  Don't use this for
actual release builds of course.
> improve scripts/genRelease: allow test builds with dirty git.

- include/ofxImageEffect.h
- include/ofxParam.h
Improve documentation
1. paramGetValue: Added a note about this only being for the GUI (kOfxActionInstanceChanged and interacts) and not for render actions.
2. paramSetValue, paramSetValueAtTime, paramEditBegin, and paramEditEnd: Added notes that they are only to be called inside kOfxActionInstanceChanged and interact actions.
3. kOfxImageEffectPropRenderScale: The list of actions where this is
required was missing many actions.
> Improve documentation for paramGetValue and kOfxImageEffectPropRenderScale

- include/ofxCore.h
- include/ofxDialog.h
- include/ofxImageEffect.h
- include/ofxMultiThread.h
- include/ofxOpenGLRender.h
- include/ofxParam.h
- include/ofxPixels.h
- include/ofxProperty.h
- constify parameters and return values when appropriate
- add half sample format (required for OpenGL)
- kOfxParamPropInteractMinimumSize is a double x 2 in Nuke
> fix various issues in ofx includes

- include/ofxCore.h
Also cleaned up usage/parallelism in comment.  Minor.
> kOfxBitDepthHalf: indicate this was added in 1.4.

- include/ofxMultiThread.h
Added V2 proposal
Adds OfxMultiThreadSuiteV2 which simplifies OfxMultiThreadSuiteV1 by removing the five *mutex calls which should really be done using OS calls. The *multiThread function pointers remain as is. This is part of API clean-up to limit suite ambiguities with regards to what an host supports or not.
This is in response to feature request: "we could have a rev of the threading API, which is slightly tidier than the current one, which allows access to that thread pool. The host still needs to tell the plugin, on a per action basis, how many threads it is allowed to use."
ALTERNATIVE: The other way to do this would be a new property on the inArgs, kOfxPropNumberThreadsAllowed, which would be the total number of threads the plugin could launch. This would need to be added to the …
> MultiTread V2 suite

- Documentation/sources/Reference/ofxCoreAPI.rst
- include/ofxCore.h
Adds OfxSetHost and a few doc notes
Please read the [contribution guidelines](https://github.com/ofxa/openfx/wiki/Extending-OpenFX-Guidelines#submit-a-proposal-or-bug-report-to-review).
Please provide a description of what this PR is meant to fix, and link it to the corresponding open issue with its tag.
Also explain how it works (if it's not going to be very clear from the code).
> Add new API call OfxSetHost

- include/ofxImageEffect.h
This addresses #75  where the host cannot know if a plug-in will use the new OfxDrawSuite to implement the draw action of the Overlay Interact. 
Setting a new kOfxImageEffectPluginPropOverlayInteractV2 is a good way to indicate the host that the plug-in's overlay interact uses the draw suite.
> Enable host to know if a plug-in uses OfxDrawSuite to draw overlays

- HostSupport/include/ofxhClip.h
- HostSupport/include/ofxhImageEffect.h
- HostSupport/include/ofxhInteract.h
- HostSupport/include/ofxhParam.h
- HostSupport/include/ofxhPropertySuite.h
- HostSupport/src/ofxhClip.cpp
- HostSupport/src/ofxhImageEffect.cpp
- HostSupport/src/ofxhInteract.cpp
- HostSupport/src/ofxhParam.cpp
- HostSupport/src/ofxhPropertySuite.cpp
- Support/Library/ofxsCore.cpp
- Support/Library/ofxsImageEffect.cpp
- Support/Library/ofxsInteract.cpp
- Support/Library/ofxsParams.cpp
- Support/Library/ofxsProperty.cpp
- Support/include/ofxsCore.h
- Support/include/ofxsImageEffect.h
- Support/include/ofxsMemory.h
- Support/include/ofxsParam.h
Removes dynamic exception specifications and fixes "catching polymorphic type" warnings. Exception specifications were deprecated in C++11 and removed in C++17. This should address [ issue  #82](https://github.com/AcademySoftwareFoundation/openfx/issues/82).
> Remove deprecated exception specifications.

- HostSupport/examples/hostDemo.cpp
- HostSupport/include/ofxhImageEffectAPI.h
- HostSupport/src/ofxhImageEffectAPI.cpp
- Support/Library/ofxsImageEffect.cpp
- Support/Plugins/Basic/basic.cpp
- Support/Plugins/Field/field.cpp
- Support/Plugins/Generator/noise.cpp
- Support/Plugins/Invert/invert.cpp
- Support/Plugins/MultiBundle/multibundle1.cpp
- Support/Plugins/MultiBundle/multibundle2.cpp
- Support/Plugins/Retimer/retimer.cpp
- Support/Plugins/Tester/Tester.cpp
- Support/Plugins/Transition/crossFade.cpp
- Support/include/ofxsImageEffect.h
- Support/include/ofxsParam.h
Replaced all std::auto_ptr usage with std::unique_ptr usage. auto_ptr was deprecated in C++11 and was removed in C++17. I tried to make minimal changes that would preserve behavior and avoid changing too many function signatures.
> Replace deprecated auto_ptr with unique_ptr.

- CMakeLists.txt
- Examples/OpenGL/opengl.cpp
- HostSupport/CMakeLists.txt
- HostSupport/examples/cacheDemo.cpp
- cmake/OpenFX.cmake
- conanfile.py
- readme.md
- scripts/build-cmake.sh
- symbols/mingw.symbols
- test_package/CMakeLists.txt
- test_package/conanfile.py
- test_package/src/test_package.cpp
Changes to https://github.com/AcademySoftwareFoundation/openfx/pull/109 that get the code building with Conan 1.59 and Conan 2.0.x. I've verified that these changes work on Windows (CMD & MSYS) and Ubuntu.
> Fix Windows build and get recipe working with 1.59 and 2.0.1

- .github/workflows/build.yml
> CI: Add build on VFX Reference Platform 2023

- Documentation/sources/Guide/Code/Example1/basics.cpp
- Documentation/sources/Guide/Code/Example2/invert.cpp
- Documentation/sources/Guide/Code/Example3/gain.cpp
- Documentation/sources/Guide/Code/Example4/saturation.cpp
- Documentation/sources/Guide/Code/Example5/circle.cpp
- Examples/Basic/basic.cpp
- Examples/Custom/custom.cpp
- Examples/DepthConverter/depthConverter.cpp
- Examples/DrawSuite/drawsuite.cpp
- Examples/Invert/invert.cpp
- Examples/Makefile.master
- Examples/OpenGL/opengl.cpp
- Examples/Overlay/overlay.cpp
- Examples/Rectangle/rectangle.cpp
- Examples/Test/testProperties.cpp
- Support/Library/ofxsImageEffect.cpp
Also use __linux__, proper modern preprocessor symbol.
Closes #117.
> Fix Example Makefile to build on OSX and Linux

- include/ofxCore.h
> Add recommendation that hosts return same host & suite for all plugins in a shlib

- Documentation/sources/Reference/ofxParameter.rst
- include/ofxCore.h
- include/ofxDialog.h
- include/ofxDrawSuite.h
- include/ofxGPURender.h
- include/ofxImageEffect.h
- include/ofxMemory.h
- include/ofxMessage.h
- include/ofxMultiThread.h
- include/ofxParam.h
- include/ofxParametricParam.h
- include/ofxProgress.h
- include/ofxProperty.h
- include/ofxTimeLine.h
No code impact; please review for consistency.
> Doc cleanup

- Documentation/sources/Reference/ofxPackaging.rst
Closes #138. See that for details.
> Deprecate MacOS-x86-64 install folder in spec (doc)

- Examples/GPUGain/GPUGain.cpp
- Examples/GPUGain/OpenCLKernel.cpp
- Support/Library/ofxsImageEffect.cpp
- Support/include/ofxsImageEffect.h
- Support/include/ofxsProcessing.h
- include/ofxGPURender.h
- include/ofxImageEffect.h
- Modify ofxGPURender.h to support OpenCL Images
- Add kOfxImageEffectActionBeginSequenceRender and kOfxImageEffectActionEndSequenceRender as required actions for some CUDA/Metal/OpenCL properties where they were not listed
- Also make documentation edits in the same header
- Modify GPUGain example to also support OpenCL Images and show how to disambiguate in the case where a plug-in supports both OpenCL Buffers and OpenCL Images
> Add OpenCL Image support to the updated GPU rendering extension:

- Support/Library/ofxsImageEffect.cpp
Some variables like kOfxImageEffectPropOpenCLRenderSupported are used in ofxsImageEffect and are declared in ofxGPURender.h. So this file should always be included even if we build without OFX_SUPPORTS_OPENGLRENDER.
> Fix missing GPU include

- Documentation/sources/Reference/ofxParameter.rst
- Support/Plugins/ChoiceParams/choiceparams.cpp
* Set defaults for StrChoice params in examples
* Update doc to say that Choice and StrChoice params should use first defined option if the plugin doesn't specify a default
* Fix plugin grouping for Support/Plugins/ChoiceParams
See also PR #133.
> Fix issues with Choice and StrChoice params, per #146

- install.md
- readme.md
The instructions in `install.md` were very out of date, and the ones in `readme.md` weren't great either. This moves all of it into `install.md` and adds some detail, with pointers to other relevant files.
> Update build/install docs

- Examples/ColourSpace/colourspace.cpp
Do not set kOfxImageClipPropPreferredColourspaces for the output clip. Handle kOfxImageEffectActionGetOutputColourspace to set the output colourspace.
> Update the ColourSpace example

- Documentation/sources/Reference/suites/ofxTimeLineSuiteReference.rst
The documentation page for `OfxTimeLineSuiteV1` was incorrectly referencing `OfxImageEffectSuiteV1` instead.
> Fix doxygen reference for OfxTimeLineSuiteV1

- include/ofx-native-v1.5_aces-v1.3_ocio-v2.3.h
- scripts/genColour
This was missing due to a typo in genColour.
> Colour: added srgb_encoded_p3d65_tx to core

- .github/workflows/build.yml
- Examples/ColourSpace/colourspace.cpp
Example now includes 3 plugins, to exercise Basic, Core and Full styles.
> Update colourspace example for more complete coverage

- include/ofxImageEffect.h
- release-notes.md
Plugins should be able to opt-in to host's LUT generators (or other non-spatial renders), and hosts need a way of indicating to the plugin that the current render requires rendering without spatial awareness. 
Resolve has already defined an extension `OfxImageEffectPropNoSpatialAwareness`, so I propose using that for both the plugin descriptor and the read-only render argument passed by the host.
Closes #127
> Add `OfxImageEffectPropNoSpatialAwareness`

- CONTRIBUTING.md
- Documentation/sourceforge/index.html
- Documentation/sources/Guide/Code/Example1/basics.cpp
- Documentation/sources/Guide/Code/Example2/invert.cpp
- Documentation/sources/Guide/Code/Example3/gain.cpp
- Documentation/sources/Guide/Code/Example4/saturation.cpp
- Documentation/sources/Guide/Code/Example5/circle.cpp
- Documentation/sources/Guide/ofxExample1_Basics.rst
- Documentation/sources/Guide/ofxExample4_Saturation.rst
- Documentation/sources/Guide/ofxExample5_Circle.rst
- Documentation/sources/Guide/ofxExamples.rst
- Documentation/sources/Reference/apiChanges_1_2_Chapter.rst
- Documentation/sources/Reference/ofxClipPreferences.rst
- Documentation/sources/Reference/ofxCoordSystem.rst
- Documentation/sources/Reference/ofxImageClip.rst
- Documentation/sources/Reference/ofxImageEffectContexts.rst
- Documentation/sources/Reference/ofxParameter.rst
- Documentation/sources/Reference/ofxProcessingArch.rst
- Documentation/sources/Reference/ofxPropertiesByObject.rst
- Documentation/sources/Reference/ofxRendering.rst
- Documentation/sources/Reference/ofxStructure.rst
> Fix typos in Documentation

- HostSupport/examples/cacheDemo.cpp
- HostSupport/examples/hostDemoClipInstance.cpp
- HostSupport/examples/hostDemoClipInstance.h
- HostSupport/examples/hostDemoEffectInstance.h
- HostSupport/examples/hostDemoHostDescriptor.cpp
- HostSupport/include/ofxhClip.h
- HostSupport/include/ofxhImageEffect.h
- HostSupport/include/ofxhInteract.h
- HostSupport/include/ofxhParam.h
- HostSupport/include/ofxhPluginCache.h
- HostSupport/include/ofxhPropertySuite.h
- HostSupport/include/ofxhUtilities.h
- HostSupport/src/ofxhClip.cpp
- HostSupport/src/ofxhHost.cpp
- HostSupport/src/ofxhImageEffect.cpp
- HostSupport/src/ofxhInteract.cpp
- HostSupport/src/ofxhPropertySuite.cpp
- include/ofxImageEffect.h
> Fix typos in HostSupport subdirectory
